### ISSUE TITLE
DCP7065DN invalid header magic number error

### ISSUE THREAD

**Issue by tecufanujacu** [rumpeltux/brother-scand#8]
As per the title, i tried the software with a DCP7065DN but I have this error:

```
ERR   data_channel.c:353: 192.168.1.4: invalid header magic number (3 != 0x07)
{
  00000000: 8203 0001 0084 8008 7a50                | ........zP
}
ERR   data_channel.c:739: 192.168.1.4: failed to process data. The channel will be closed.
DEBUG data_channel.c:746: data_channel->process_cb = data_channel_set_paused;

```

If needed I can provide the full log.
Is there any chance to support this device?

**Comment by rumpeltux** [comment]
Likely the protocol is going to be quite different. Contributions are welcome, but I won’t be able to add support for this device on my own.

**Comment by tecufanujacu** [comment]
Yes I know, before now I have never played with scanners protocol and I'm studying, Just today I found something in the github to read the protocol. Do you have some input?
